replicaCount: 1
namespace: matomo
persistence:
  enabled: true
  storageClass: "cephfs"
  accessModes:
    - ReadWriteOnce
  size: 8Gi

ingress:
  enabled: false

mariadb:
  enabled: true
  architecture: standalone
  image:
    pullPolicy: Always
  auth:
    rootPassword: "root"
    database: bitnami_matomo
    username: bn_matomo
    password: "root"
  primary:
    containerSecurityContext:
      enabled: true
      runAsUser: 10001
      runAsGroup: 10001
    persistence:
      enabled: true
      storageClass: "cephfs"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    storageClass: "cephfs"
    resourcesPreset: "micro"
    imagePullPolicy: Always

matomo:
  skipInstall: true
  persistence:
    enabled: true
    imagePullPolicy: Always
    storageClass: "cephfs"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  plugins:
    - "LoginOIDC"
  domain: "matomo.etsmtl.club"
  service:
    type: ClusterIP

image:
  pullPolicy: Always
containerSecurityContext:
  runAsGroup: 10001
  runAsUser: 10001
  readOnlyRootFilesystem: true
