replicaCount: 1

persistence:
  enabled: true
  storageClass: "cephfs"
  accessModes:
    - ReadWriteOnce
  size: 8Gi

ingress:
  enabled: false

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: "root"
    database: bitnami_matomo
    username: bn_matomo
    password: "root"
  primary:
    persistence:
      enabled: true
      storageClass: "cephfs"
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    storageClass: "cephfs"
    resourcesPreset: "micro"
  containerSecurityContext:
    enabled: true
    fsGroup: 10001
    runAsUser: 10001

matomo:
  skipInstall: true
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsUser: 10001
  persistence:
    enabled: true
    storageClass: "cephfs"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  plugins:
    - "LoginOIDC"
  domain: "matomo.etsmtl.club"
  service:
    type: ClusterIP
