apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  annotations:
    kube-score/ignore: pod-networkpolicy, container-image-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - chown -R 10001:10001 /data;
              chmod -R 770 /data;
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-storage
      containers:
        - name: vaultwarden
          image: vaultwarden/server:testing
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-storage
          ### https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: ADMIN_TOKEN

            - name: SSO_SCOPES
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_SCOPES
            - name: SSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_CLIENT_ID

            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secret
                  key: SSO_CLIENT_SECRET

            - name: SSO_ENABLED
              value: true
            - name: SSO_AUTHORITY
              value: https://auth.etsmtl.club/application/o/vaultwarden/
            - name: SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION
              value: false
            - name: SSO_CLIENT_CACHE_EXPIRATION
              value: 0
            - name: SSO_ONLY
              value: true
            - name: SSO_SIGNUPS_MATCH_EMAIL
              value: true
            - name: SSO_AUTH_ONLY_NOT_SESSION
              value: true
            - name: DOMAIN
              value: https://vaultwarden.etsmtl.club

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: 250m
              memory: 500Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 1Gi

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: vaultwarden-storage
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
